-- MySQL Script generated by MySQL Workbench
-- 02/13/18 22:00:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema phone_number_manager
-- -----------------------------------------------------
-- 电话管理系统

-- -----------------------------------------------------
-- Schema phone_number_manager
--
-- 电话管理系统
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phone_number_manager` DEFAULT CHARACTER SET utf8 ;
USE `phone_number_manager` ;

-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_subdistricts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_subdistricts` (
  `subdistrict_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '街道办事处名称',
  `telephone` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '联系电话',
  PRIMARY KEY (`subdistrict_id`),
  UNIQUE INDEX `subdistrict_name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '街道办事处表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_communities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_communities` (
  `community_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '社区名称',
  `telephone` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '联系电话',
  `actual_number` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT '指标',
  `subdistrict_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '街道办事处所属ID',
  PRIMARY KEY (`community_id`),
  UNIQUE INDEX `community_name_UNIQUE` (`name` ASC),
  INDEX `fk_communities_subdistricts_idx` (`subdistrict_id` ASC),
  CONSTRAINT `fk_communities_subdistricts`
    FOREIGN KEY (`subdistrict_id`)
    REFERENCES `phone_number_manager`.`pm_subdistricts` (`subdistrict_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '社区表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_community_residents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_community_residents` (
  `community_resident_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '居民姓名',
  `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '住址',
  `phones` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '居民电话，共三个，用英文逗号分隔',
  `subcontractor` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '分包人员',
  `edit_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '编辑时间',
  `is_commited` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已经进行过提交，0未提交，1已提交',
  `community_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '社区所属ID',
  PRIMARY KEY (`community_resident_id`),
  INDEX `fk_community_residents_communities1_idx` (`community_id` ASC),
  UNIQUE INDEX `name_address_UNIQUE` (`name` ASC, `address` ASC),
  CONSTRAINT `fk_community_residents_communities1`
    FOREIGN KEY (`community_id`)
    REFERENCES `phone_number_manager`.`pm_communities` (`community_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '社区居民信息表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_roles` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '角色名称',
  `description` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色描述',
  `higher_role` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上级角色',
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_system_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_system_users` (
  `system_user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '用户名称',
  `password` CHAR(88) NOT NULL DEFAULT '' COMMENT '用户密码',
  `login_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '登录时间',
  `login_ip` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '登录IP',
  `is_locked` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已锁定，0未锁定，1已锁定',
  `role_location_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色定位ID',
  `role_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色所属ID',
  PRIMARY KEY (`system_user_id`),
  INDEX `fk_pm_system_users_pm_roles1_idx` (`role_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_pm_system_users_pm_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `phone_number_manager`.`pm_roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '系统用户表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_privileges` (
  `privilege_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '权限名称',
  `constraint_auth` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '约束名称',
  `uri` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '访问URI地址',
  `higher_privilege` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上级权限',
  `icon_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '图标名称',
  `orders` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '菜单排序',
  `is_display` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否在菜单栏中显示，0不显示，1显示',
  PRIMARY KEY (`privilege_id`),
  UNIQUE INDEX `privilege_name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `constraint_auth_UNIQUE` (`constraint_auth` ASC))
ENGINE = InnoDB
COMMENT = '用户权限表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_roles_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_roles_privileges` (
  `role_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色所属ID',
  `privilege_id` INT UNSIGNED NOT NULL COMMENT '权限所属ID',
  PRIMARY KEY (`role_id`, `privilege_id`),
  INDEX `fk_pm_roles_has_pm_privileges_pm_privileges1_idx` (`privilege_id` ASC),
  INDEX `fk_pm_roles_has_pm_privileges_pm_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_pm_roles_has_pm_privileges_pm_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `phone_number_manager`.`pm_roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pm_roles_has_pm_privileges_pm_privileges1`
    FOREIGN KEY (`privilege_id`)
    REFERENCES `phone_number_manager`.`pm_privileges` (`privilege_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户角色与权限中间表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_categories` (
  `category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '分类名称',
  `parent_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父类编号',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
COMMENT = '文章分类表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_articles` (
  `article_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '文章标题',
  `content` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '文章内容',
  `system_user_id` INT UNSIGNED NOT NULL COMMENT '系统用户所属编号',
  `category_id` INT UNSIGNED NOT NULL COMMENT '分类编号',
  PRIMARY KEY (`article_id`),
  INDEX `fk_pm_articles_pm_system_users1_idx` (`system_user_id` ASC),
  INDEX `fk_pm_articles_pm_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_pm_articles_pm_system_users1`
    FOREIGN KEY (`system_user_id`)
    REFERENCES `phone_number_manager`.`pm_system_users` (`system_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pm_articles_pm_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `phone_number_manager`.`pm_categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '系统文章表';


-- -----------------------------------------------------
-- Table `phone_number_manager`.`pm_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number_manager`.`pm_configurations` (
  `key` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '系统配置项关键字名称',
  `type` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '系统配置项类型，0未知类型，1布尔类型，2字符串类型，3数值类型，4系统用户类型',
  `value` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '配置内容',
  `description` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '配置项描述',
  `key_is_changed` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '系统配置项关键字名称是否允许更改。0不允许，1允许',
  PRIMARY KEY (`key`))
ENGINE = InnoDB
COMMENT = '系统配置表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
