-- MySQL Script generated by MySQL Workbench
-- 11/27/18 23:17:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema phone_number
-- -----------------------------------------------------
-- 电话管理系统

-- -----------------------------------------------------
-- Schema phone_number
--
-- 电话管理系统
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phone_number` DEFAULT CHARACTER SET utf8;
USE `phone_number`;

-- -----------------------------------------------------
-- Table `phone_number`.`pm_subdistricts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_subdistricts` (
    `subdistrict_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '街道办事处名称',
  `telephone` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '联系电话',
  PRIMARY KEY (`subdistrict_id`),
  UNIQUE INDEX `subdistrict_name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = '街道办事处表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_communities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_communities` (
    `community_id`   BIGINT UNSIGNED      NOT NULL AUTO_INCREMENT,
    `name`           VARCHAR(10)          NOT NULL DEFAULT '' COMMENT '社区名称',
    `telephone`      VARCHAR(15)          NOT NULL DEFAULT '' COMMENT '联系电话',
    `actual_number`  SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT '指标',
    `subdistrict_id` BIGINT UNSIGNED      NOT NULL DEFAULT 0 COMMENT '街道办事处所属ID',
    PRIMARY KEY (`community_id`),
    UNIQUE INDEX `community_name_UNIQUE`(`name` ASC),
    INDEX `fk_communities_subdistricts_idx`(`subdistrict_id` ASC),
    CONSTRAINT `fk_communities_subdistricts`
    FOREIGN KEY (`subdistrict_id`)
        REFERENCES `phone_number`.`pm_subdistricts`(`subdistrict_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '社区表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_subcontractors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_subcontractors` (
    `subcontractor_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`             VARCHAR(10)     NOT NULL DEFAULT '' COMMENT '分包人姓名',
    `telephone`        VARCHAR(15)     NOT NULL DEFAULT '' COMMENT '分包人联系方式',
    `community_id`     BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '分包人所属社区编号',
    PRIMARY KEY (`subcontractor_id`),
    UNIQUE INDEX `name_UNIQUE`(`name` ASC),
    INDEX `fk_pm_subcontractor_pm_communities1_idx`(`community_id` ASC),
    UNIQUE INDEX `telephone_UNIQUE`(`telephone` ASC),
    CONSTRAINT `fk_pm_subcontractor_pm_communities1`
        FOREIGN KEY (`community_id`)
            REFERENCES `phone_number`.`pm_communities`(`community_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    COMMENT = '社区分包人表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_community_residents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_community_residents` (
    `community_resident_id` BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `name`                  VARCHAR(10)         NOT NULL DEFAULT '' COMMENT '居民姓名',
    `address`               VARCHAR(255)        NOT NULL DEFAULT '' COMMENT '住址',
    `phones`                VARCHAR(50)         NOT NULL DEFAULT '' COMMENT '居民电话，共三个，用英文逗号分隔',
    `edit_time`             TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '编辑时间',
    `is_commited`           TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已经进行过提交，0未提交，1已提交',
    `community_id`          BIGINT UNSIGNED     NOT NULL DEFAULT 0 COMMENT '社区所属ID',
    `subcontractor_id`      BIGINT UNSIGNED     NOT NULL DEFAULT 0 COMMENT '所属社区分包人编号',
    PRIMARY KEY (`community_resident_id`),
    INDEX `fk_community_residents_communities1_idx`(`community_id` ASC),
    UNIQUE INDEX `name_address_UNIQUE`(`name` ASC, `address` ASC),
    INDEX `fk_pm_community_residents_pm_subcontractors1_idx`(`subcontractor_id` ASC),
    CONSTRAINT `fk_community_residents_communities1`
    FOREIGN KEY (`community_id`)
        REFERENCES `phone_number`.`pm_communities`(`community_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `fk_pm_community_residents_pm_subcontractors1`
        FOREIGN KEY (`subcontractor_id`)
            REFERENCES `phone_number`.`pm_subcontractors`(`subcontractor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '社区居民信息表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_roles` (
    `role_id`     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(10)     NOT NULL DEFAULT '' COMMENT '角色名称',
    `description` VARCHAR(50)     NOT NULL DEFAULT '' COMMENT '角色描述',
    `higher_role` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上级角色',
    PRIMARY KEY (`role_id`),
    UNIQUE INDEX `role_name_UNIQUE`(`name` ASC)
)
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_system_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_system_users` (
    `system_user_id`   BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `username`         VARCHAR(10)         NOT NULL DEFAULT '' COMMENT '用户名称',
    `password`         CHAR(88)            NOT NULL DEFAULT '' COMMENT '用户密码',
    `login_time`       TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '登录时间',
    `login_ip`         VARCHAR(15)         NOT NULL DEFAULT '' COMMENT '登录IP',
    `is_locked`        TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已锁定，0未锁定，1已锁定',
    `role_location_id` BIGINT UNSIGNED     NOT NULL DEFAULT 0 COMMENT '角色定位ID',
    `role_id`          BIGINT UNSIGNED     NOT NULL DEFAULT 0 COMMENT '角色所属ID',
    PRIMARY KEY (`system_user_id`),
    INDEX `fk_pm_system_users_pm_roles1_idx`(`role_id` ASC),
    UNIQUE INDEX `username_UNIQUE`(`username` ASC),
    CONSTRAINT `fk_pm_system_users_pm_roles1`
    FOREIGN KEY (`role_id`)
        REFERENCES `phone_number`.`pm_roles`(`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '系统用户表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_privileges` (
    `privilege_id`     BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
    `name`             VARCHAR(30)         NOT NULL DEFAULT '' COMMENT '权限名称',
    `constraint_auth`  VARCHAR(50)         NOT NULL DEFAULT '' COMMENT '约束名称',
    `uri`              VARCHAR(100)        NOT NULL DEFAULT '' COMMENT '访问URI地址',
    `higher_privilege` BIGINT UNSIGNED     NOT NULL DEFAULT 0 COMMENT '上级权限',
    `icon_name`        VARCHAR(50)         NOT NULL DEFAULT '' COMMENT '图标名称',
    `orders`           TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '菜单排序',
    `is_display`       TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否在菜单栏中显示，0不显示，1显示',
    PRIMARY KEY (`privilege_id`),
    UNIQUE INDEX `privilege_name_UNIQUE`(`name` ASC),
    UNIQUE INDEX `constraint_auth_UNIQUE`(`constraint_auth` ASC)
)
ENGINE = InnoDB
COMMENT = '用户权限表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_roles_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_roles_privileges` (
    `role_id`      BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色所属ID',
    `privilege_id` BIGINT UNSIGNED NOT NULL COMMENT '权限所属ID',
  PRIMARY KEY (`role_id`, `privilege_id`),
  INDEX `fk_pm_roles_has_pm_privileges_pm_privileges1_idx` (`privilege_id` ASC),
  INDEX `fk_pm_roles_has_pm_privileges_pm_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_pm_roles_has_pm_privileges_pm_roles1`
    FOREIGN KEY (`role_id`)
        REFERENCES `phone_number`.`pm_roles`(`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pm_roles_has_pm_privileges_pm_privileges1`
    FOREIGN KEY (`privilege_id`)
        REFERENCES `phone_number`.`pm_privileges`(`privilege_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户角色与权限中间表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_categories` (
    `category_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(15)     NOT NULL DEFAULT '' COMMENT '分类名称',
    `parent_id`   BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父类编号',
    PRIMARY KEY (`category_id`)
)
ENGINE = InnoDB
COMMENT = '文章分类表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_articles` (
    `article_id`     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title`          VARCHAR(30)     NOT NULL DEFAULT '' COMMENT '文章标题',
    `content`        VARCHAR(500)    NOT NULL DEFAULT '' COMMENT '文章内容',
    `system_user_id` BIGINT UNSIGNED NOT NULL COMMENT '系统用户所属编号',
    `category_id`    BIGINT UNSIGNED NOT NULL COMMENT '分类编号',
    PRIMARY KEY (`article_id`),
    INDEX `fk_pm_articles_pm_system_users1_idx`(`system_user_id` ASC),
    INDEX `fk_pm_articles_pm_categories1_idx`(`category_id` ASC),
    CONSTRAINT `fk_pm_articles_pm_system_users1`
    FOREIGN KEY (`system_user_id`)
        REFERENCES `phone_number`.`pm_system_users`(`system_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_pm_articles_pm_categories1`
    FOREIGN KEY (`category_id`)
        REFERENCES `phone_number`.`pm_categories`(`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '系统文章表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_configurations` (
  `key` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '系统配置项关键字名称',
  `type` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '系统配置项类型，0未知类型，1布尔类型，2字符串类型，3数值类型，4系统用户类型',
  `value` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '配置内容',
  `description` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '配置项描述',
  `key_is_changed` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '系统配置项关键字名称是否允许更改。0不允许，1允许',
  PRIMARY KEY (`key`))
ENGINE = InnoDB
COMMENT = '系统配置表';


-- -----------------------------------------------------
-- Table `phone_number`.`pm_dormitory_managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone_number`.`pm_dormitory_managers` (
    `dormitory_manager_id` BIGINT UNSIGNED     NOT NULL COMMENT '楼片长编号',
    `id`                   VARCHAR(30)         NOT NULL DEFAULT '' COMMENT '编号',
    `name`                 VARCHAR(10)         NOT NULL DEFAULT '' COMMENT '楼片长',
    `sex`                  TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '性别，0男，1女，2未知',
    `birthday`             TIMESTAMP           NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '出生年月',
    `policital_status`     TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '政治面貌，0群众，1党员，2团员，3预备党员，4预备团员',
    `work_status`          TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '工作状况，0在职，1退休，2无业',
    `education`            TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '学历，0文盲，1小学，2初中，3中专，4高中，5大专，6本科，7硕士研究生，8博士研究生',
    `address`              VARCHAR(255)        NOT NULL DEFAULT '' COMMENT '家庭住址',
    `manager_address`      VARCHAR(255)        NOT NULL DEFAULT '' COMMENT '管理的地址',
    `manager_count`        INT UNSIGNED        NOT NULL DEFAULT 0 COMMENT '管理的户数',
    `telephones`           VARCHAR(30)         NOT NULL DEFAULT '' COMMENT '联系方式，固定电话与移动电话用英文逗号分隔',
    `subcontractor_id`     BIGINT UNSIGNED     NOT NULL DEFAULT 0 COMMENT '社区分包人编号',
    PRIMARY KEY (`dormitory_manager_id`),
    UNIQUE INDEX `id_UNIQUE`(`id` ASC),
    INDEX `fk_pm_dormitory_managers_pm_subcontractors1_idx`(`subcontractor_id` ASC),
    CONSTRAINT `fk_pm_dormitory_managers_pm_subcontractors1`
        FOREIGN KEY (`subcontractor_id`)
            REFERENCES `phone_number`.`pm_subcontractors`(`subcontractor_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    COMMENT = '楼片长信息表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
