export default [
  {
    name: '登录',
    path: '/account/login',
    component: './login',
    layout: false,
    menuRender: false,
    headerRender: false,
    menuHeaderRender: false,
  },
  {
    path: '/resident',
    name: './resident',
    component: './resident',
    access: 'normalRouteFilter',
  },
  {
    path: '/dormitory',
    name: './dormitory',
    component: './dormitory',
    access: 'normalRouteFilter',
  },
  {
    path: '/company',
    name: './company',
    component: './company',
    access: 'normalRouteFilter',
  },
  {
    path: '/company/subcontractor',
    name: './subcontractor',
    component: './subcontractor',
    access: 'normalRouteFilter',
  },
  {
    path: '/system/user',
    name: './user',
    component: './user',
    access: 'normalRouteFilter',
  },
  {
    path: '/system/permission',
    name: './permission',
    component: './permission',
    access: 'normalRouteFilter',
  },
  {
    path: '/system/configuration',
    name: './configuration',
    component: './configuration',
    access: 'normalRouteFilter',
  },
  { path: '/welcome', name: '/welcome', component: './welcome' },
  { path: '/', redirect: '/welcome' },
  { component: './404' },
];
