export default [
  {
    name: '登录',
    path: '/account/login',
    component: './account/Login',
    layout: false,
    menuRender: false,
    headerRender: false,
    menuHeaderRender: false,
  },
  {
    path: '/resident',
    name: '社区居民信息列表',
    component: './resident',
    access: 'normalRouteFilter',
  },
  {
    path: '/dormitory',
    name: '社区居民楼片长信息列表',
    component: './dormitory',
    access: 'normalRouteFilter',
  },
  {
    path: '/company',
    name: '单位列表',
    component: './company',
    access: 'normalRouteFilter',
  },
  {
    path: '/company/subcontractor',
    name: '社区分包人员列表',
    component: './subcontractor',
    access: 'normalRouteFilter',
  },
  {
    path: '/system/user',
    name: '系统用户列表',
    component: './user',
    access: 'normalRouteFilter',
  },
  {
    path: '/system/permission',
    name: '系统权限列表',
    component: './permission',
    access: 'normalRouteFilter',
  },
  {
    path: '/system/configuration',
    name: '系统配置列表',
    component: './configuration',
    access: 'normalRouteFilter',
  },
  { path: '/welcome', name: '欢迎', component: './welcome' },
  { path: '/', redirect: '/welcome' },
  { component: './404' },
];
